ALTER TABLE "OpeningFund" ADD COLUMN "goldWeight" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "OpeningFund" ADD COLUMN "goldAvgPrice" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "OpeningFund" ADD COLUMN "goldValuation" DECIMAL NOT NULL DEFAULT 0;
